// <auto-generated />
using System;
using CategoryMS_Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CategoryMS_API.Migrations
{
    [DbContext(typeof(CategoryMsDbContext))]
    partial class CategoryMsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CategoryMS_Core.Models.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("6f1236ed-bb75-4503-8fbb-3aaf916fd682"),
                            CategoryName = "Legs"
                        },
                        new
                        {
                            CategoryId = new Guid("9b617966-f433-4666-b91c-f1308fe7250d"),
                            CategoryName = "Abs"
                        },
                        new
                        {
                            CategoryId = new Guid("d20436a6-493c-4752-97af-cbf54efac614"),
                            CategoryName = "Chest"
                        },
                        new
                        {
                            CategoryId = new Guid("190706f5-47ac-4fdd-916b-f26ff05c8b6c"),
                            CategoryName = "Shoulders"
                        },
                        new
                        {
                            CategoryId = new Guid("d8983703-3b47-4db8-a4c9-24e132444f20"),
                            CategoryName = "Biceps"
                        },
                        new
                        {
                            CategoryId = new Guid("84fdb065-8c4a-464d-9fcf-3b977e79cf35"),
                            CategoryName = "Triceps"
                        },
                        new
                        {
                            CategoryId = new Guid("61574778-0381-4cfc-a18a-58d67876284b"),
                            CategoryName = "Forearms"
                        },
                        new
                        {
                            CategoryId = new Guid("3f3ab9f7-7930-4735-affc-8bb7ec9a1e0e"),
                            CategoryName = "Back"
                        },
                        new
                        {
                            CategoryId = new Guid("87ffcaa0-657f-4a25-a4f9-5be94cdda8d4"),
                            CategoryName = "Cardio"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
